export const CHAINS = [
  {
    name: "Optimism",
    shortName: "Oeth",
    chainID: "eip155:10",
    shortChainID: "10",
    prefix: "oeth",
  },
  {
    name: "Binance Smart Chain Mainnet",
    shortName: "BNB",
    chainID: "eip155:56",
    shortChainID: "56",
    prefix: "bnb",
  },
  {
    name: "Celo Mainnet",
    shortName: "CELO",
    chainID: "eip155:42220",
    shortChainID: "42220",
    prefix: "celo",
  },
  {
    name: "Gnosis",
    shortName: "gno",
    chainID: "eip155:100",
    shortChainID: "100",
    prefix: "gno",
  },
  {
    name: "Ethereum Mainnet",
    shortName: "Ethereum",
    chainID: "eip155:1",
    shortChainID: "1",
    prefix: "eth",
  },
  {
    name: "Polygon Testnet Mumbai",
    shortName: "maticmum",
    chainID: "eip155:80001",
    shortChainID: "80001",
    prefix: "maticmum",
  },
  {
    name: "Arbitrum One",
    shortName: "Arb1",
    chainID: "eip155:42161",
    shortChainID: "42161",
    prefix: "arb1",
  },
  {
    name: "Avalanche C-Chain",
    shortName: "Avalanche",
    chainID: "eip155:43114",
    shortChainID: "43114",
    prefix: "avax",
  },
  {
    name: "Moonbeam",
    shortName: "mbeam",
    chainID: "eip155:1284",
    shortChainID: "1284",
    prefix: "mbeam",
  },
  {
    name: "Ethereum Testnet Görli",
    shortName: "Gor",
    chainID: "eip155:5",
    shortChainID: "5",
    prefix: "gor",
  },
  {
    name: "Polygon Mainnet",
    shortName: "Polygon",
    chainID: "eip155:137",
    shortChainID: "137",
    prefix: "matic",
  },
]
