// Generated by @wagmi/cli@0.1.3 on 2/23/2023 at 2:27:12 PM
import {
  useContract,
  UseContractConfig,
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
} from "wagmi"
import { WriteContractMode, PrepareWriteContractResult } from "wagmi/actions"

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// erc721
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc721ABI = [
  {
    type: "event",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "spender", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
    ],
    name: "Approval",
  },
  {
    type: "event",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "operator", type: "address", indexed: true },
      { name: "approved", type: "bool", indexed: false },
    ],
    name: "ApprovalForAll",
  },
  {
    type: "event",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
    ],
    name: "Transfer",
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "spender", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "owner", type: "address" },
      { name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ name: "", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ name: "owner", type: "address" }],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "id", type: "uint256" },
      { name: "data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "operator", type: "address" },
      { name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "index", type: "uint256" }],
    name: "tokenByIndex",
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "owner", type: "address" },
      { name: "index", type: "uint256" },
    ],
    name: "tokenByIndex",
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ name: "", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "sender", type: "address" },
      { name: "recipient", type: "address" },
      { name: "tokeId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// erc721Mech
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc721MechABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_tokenId", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
      { name: "operation", internalType: "enum Enum.Operation", type: "uint8" },
      { name: "txGas", internalType: "uint256", type: "uint256" },
    ],
    name: "exec",
    outputs: [{ name: "success", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
      { name: "operation", internalType: "enum Enum.Operation", type: "uint8" },
      { name: "txGas", internalType: "uint256", type: "uint256" },
    ],
    name: "execReturnData",
    outputs: [
      { name: "success", internalType: "bool", type: "bool" },
      { name: "returnData", internalType: "bytes", type: "bytes" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "signer", internalType: "address", type: "address" }],
    name: "isOperator",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "hash", internalType: "bytes32", type: "bytes32" },
      { name: "signature", internalType: "bytes", type: "bytes" },
    ],
    name: "isValidSignature",
    outputs: [{ name: "magicValue", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC721Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "initParams", internalType: "bytes", type: "bytes" }],
    name: "setUp",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "token",
    outputs: [{ name: "", internalType: "contract IERC721", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "tokenId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "tokensReceived",
    outputs: [],
  },
  { stateMutability: "payable", type: "receive" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link erc721ABI}__.
 */
export function useErc721(config: Omit<UseContractConfig, "abi"> = {} as any) {
  return useContract({ abi: erc721ABI, ...config })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__.
 */
export function useErc721Read<TFunctionName extends string>(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, TFunctionName>,
    "abi"
  > = {} as any
) {
  return useContractRead({ abi: erc721ABI, ...config } as UseContractReadConfig<
    typeof erc721ABI,
    TFunctionName
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"balanceOf"`.
 */
export function useErc721BalanceOf(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "balanceOf">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "balanceOf",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "balanceOf">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"getApproved"`.
 */
export function useErc721GetApproved(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "getApproved">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "getApproved",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "getApproved">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"isApprovedForAll"`.
 */
export function useErc721IsApprovedForAll(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "isApprovedForAll">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "isApprovedForAll",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "isApprovedForAll">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"name"`.
 */
export function useErc721Name(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "name">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "name",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "name">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"ownerOf"`.
 */
export function useErc721OwnerOf(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "ownerOf">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "ownerOf",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "ownerOf">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"symbol"`.
 */
export function useErc721Symbol(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "symbol">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "symbol",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "symbol">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"tokenByIndex"`.
 */
export function useErc721TokenByIndex(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "tokenByIndex">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "tokenByIndex",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "tokenByIndex">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"tokenURI"`.
 */
export function useErc721TokenUri(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "tokenURI">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "tokenURI",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "tokenURI">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"totalSupply"`.
 */
export function useErc721TotalSupply(
  config: Omit<
    UseContractReadConfig<typeof erc721ABI, "totalSupply">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721ABI,
    functionName: "totalSupply",
    ...config,
  } as UseContractReadConfig<typeof erc721ABI, "totalSupply">)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721ABI}__.
 */
export function useErc721Write<
  TMode extends WriteContractMode,
  TFunctionName extends string
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721ABI, string>["abi"],
        TFunctionName
      >
    : UseContractWriteConfig<TMode, typeof erc721ABI, TFunctionName> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721ABI, TFunctionName>({
    abi: erc721ABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"approve"`.
 */
export function useErc721Approve<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721ABI, "approve">["abi"],
        "approve"
      > & { functionName?: "approve" }
    : UseContractWriteConfig<TMode, typeof erc721ABI, "approve"> & {
        abi?: never
        functionName?: "approve"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721ABI, "approve">({
    abi: erc721ABI,
    functionName: "approve",
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"safeTransferFrom"`.
 */
export function useErc721SafeTransferFrom<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721ABI, "safeTransferFrom">["abi"],
        "safeTransferFrom"
      > & { functionName?: "safeTransferFrom" }
    : UseContractWriteConfig<TMode, typeof erc721ABI, "safeTransferFrom"> & {
        abi?: never
        functionName?: "safeTransferFrom"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721ABI, "safeTransferFrom">({
    abi: erc721ABI,
    functionName: "safeTransferFrom",
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"setApprovalForAll"`.
 */
export function useErc721SetApprovalForAll<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof erc721ABI,
          "setApprovalForAll"
        >["abi"],
        "setApprovalForAll"
      > & { functionName?: "setApprovalForAll" }
    : UseContractWriteConfig<TMode, typeof erc721ABI, "setApprovalForAll"> & {
        abi?: never
        functionName?: "setApprovalForAll"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721ABI, "setApprovalForAll">({
    abi: erc721ABI,
    functionName: "setApprovalForAll",
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"transferFrom"`.
 */
export function useErc721TransferFrom<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721ABI, "transferFrom">["abi"],
        "transferFrom"
      > & { functionName?: "transferFrom" }
    : UseContractWriteConfig<TMode, typeof erc721ABI, "transferFrom"> & {
        abi?: never
        functionName?: "transferFrom"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721ABI, "transferFrom">({
    abi: erc721ABI,
    functionName: "transferFrom",
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721ABI}__.
 */
export function usePrepareErc721Write<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721ABI, TFunctionName>,
    "abi"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721ABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721ABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"approve"`.
 */
export function usePrepareErc721Approve(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721ABI, "approve">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721ABI,
    functionName: "approve",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721ABI, "approve">)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"safeTransferFrom"`.
 */
export function usePrepareErc721SafeTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721ABI, "safeTransferFrom">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721ABI,
    functionName: "safeTransferFrom",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721ABI, "safeTransferFrom">)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"setApprovalForAll"`.
 */
export function usePrepareErc721SetApprovalForAll(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721ABI, "setApprovalForAll">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721ABI,
    functionName: "setApprovalForAll",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721ABI, "setApprovalForAll">)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721ABI}__ and `functionName` set to `"transferFrom"`.
 */
export function usePrepareErc721TransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721ABI, "transferFrom">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721ABI,
    functionName: "transferFrom",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721ABI, "transferFrom">)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link erc721ABI}__.
 */
export function useErc721Event<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof erc721ABI, TEventName>,
    "abi"
  > = {} as any
) {
  return useContractEvent({
    abi: erc721ABI,
    ...config,
  } as UseContractEventConfig<typeof erc721ABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link erc721ABI}__ and `eventName` set to `"Approval"`.
 */
export function useErc721ApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof erc721ABI, "Approval">,
    "abi" | "eventName"
  > = {} as any
) {
  return useContractEvent({
    abi: erc721ABI,
    eventName: "Approval",
    ...config,
  } as UseContractEventConfig<typeof erc721ABI, "Approval">)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link erc721ABI}__ and `eventName` set to `"ApprovalForAll"`.
 */
export function useErc721ApprovalForAllEvent(
  config: Omit<
    UseContractEventConfig<typeof erc721ABI, "ApprovalForAll">,
    "abi" | "eventName"
  > = {} as any
) {
  return useContractEvent({
    abi: erc721ABI,
    eventName: "ApprovalForAll",
    ...config,
  } as UseContractEventConfig<typeof erc721ABI, "ApprovalForAll">)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link erc721ABI}__ and `eventName` set to `"Transfer"`.
 */
export function useErc721TransferEvent(
  config: Omit<
    UseContractEventConfig<typeof erc721ABI, "Transfer">,
    "abi" | "eventName"
  > = {} as any
) {
  return useContractEvent({
    abi: erc721ABI,
    eventName: "Transfer",
    ...config,
  } as UseContractEventConfig<typeof erc721ABI, "Transfer">)
}

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link erc721MechABI}__.
 */
export function useErc721Mech(
  config: Omit<UseContractConfig, "abi"> = {} as any
) {
  return useContract({ abi: erc721MechABI, ...config })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__.
 */
export function useErc721MechRead<TFunctionName extends string>(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, TFunctionName>,
    "abi"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, TFunctionName>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"isOperator"`.
 */
export function useErc721MechIsOperator(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "isOperator">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "isOperator",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "isOperator">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"isValidSignature"`.
 */
export function useErc721MechIsValidSignature(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "isValidSignature">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "isValidSignature",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "isValidSignature">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"onERC1155BatchReceived"`.
 */
export function useErc721MechOnErc1155BatchReceived(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "onERC1155BatchReceived">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "onERC1155BatchReceived",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "onERC1155BatchReceived">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"onERC1155Received"`.
 */
export function useErc721MechOnErc1155Received(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "onERC1155Received">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "onERC1155Received",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "onERC1155Received">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"onERC721Received"`.
 */
export function useErc721MechOnErc721Received(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "onERC721Received">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "onERC721Received",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "onERC721Received">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"token"`.
 */
export function useErc721MechToken(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "token">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "token",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "token">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"tokenId"`.
 */
export function useErc721MechTokenId(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "tokenId">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "tokenId",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "tokenId">)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"tokensReceived"`.
 */
export function useErc721MechTokensReceived(
  config: Omit<
    UseContractReadConfig<typeof erc721MechABI, "tokensReceived">,
    "abi" | "functionName"
  > = {} as any
) {
  return useContractRead({
    abi: erc721MechABI,
    functionName: "tokensReceived",
    ...config,
  } as UseContractReadConfig<typeof erc721MechABI, "tokensReceived">)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721MechABI}__.
 */
export function useErc721MechWrite<
  TMode extends WriteContractMode,
  TFunctionName extends string
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721MechABI, string>["abi"],
        TFunctionName
      >
    : UseContractWriteConfig<TMode, typeof erc721MechABI, TFunctionName> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721MechABI, TFunctionName>({
    abi: erc721MechABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"exec"`.
 */
export function useErc721MechExec<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721MechABI, "exec">["abi"],
        "exec"
      > & { functionName?: "exec" }
    : UseContractWriteConfig<TMode, typeof erc721MechABI, "exec"> & {
        abi?: never
        functionName?: "exec"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721MechABI, "exec">({
    abi: erc721MechABI,
    functionName: "exec",
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"execReturnData"`.
 */
export function useErc721MechExecReturnData<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof erc721MechABI,
          "execReturnData"
        >["abi"],
        "execReturnData"
      > & { functionName?: "execReturnData" }
    : UseContractWriteConfig<TMode, typeof erc721MechABI, "execReturnData"> & {
        abi?: never
        functionName?: "execReturnData"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721MechABI, "execReturnData">({
    abi: erc721MechABI,
    functionName: "execReturnData",
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"setUp"`.
 */
export function useErc721MechSetUp<TMode extends WriteContractMode>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof erc721MechABI, "setUp">["abi"],
        "setUp"
      > & { functionName?: "setUp" }
    : UseContractWriteConfig<TMode, typeof erc721MechABI, "setUp"> & {
        abi?: never
        functionName?: "setUp"
      } = {} as any
) {
  return useContractWrite<TMode, typeof erc721MechABI, "setUp">({
    abi: erc721MechABI,
    functionName: "setUp",
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721MechABI}__.
 */
export function usePrepareErc721MechWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721MechABI, TFunctionName>,
    "abi"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721MechABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721MechABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"exec"`.
 */
export function usePrepareErc721MechExec(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721MechABI, "exec">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721MechABI,
    functionName: "exec",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721MechABI, "exec">)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"execReturnData"`.
 */
export function usePrepareErc721MechExecReturnData(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721MechABI, "execReturnData">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721MechABI,
    functionName: "execReturnData",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721MechABI, "execReturnData">)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link erc721MechABI}__ and `functionName` set to `"setUp"`.
 */
export function usePrepareErc721MechSetUp(
  config: Omit<
    UsePrepareContractWriteConfig<typeof erc721MechABI, "setUp">,
    "abi" | "functionName"
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: erc721MechABI,
    functionName: "setUp",
    ...config,
  } as UsePrepareContractWriteConfig<typeof erc721MechABI, "setUp">)
}
